CREATE TABLE IF NOT EXISTS tarefas(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao VARCHAR(255),
    prioridade VARCHAR(50) NOT NULL,
    data_limite DATE,
    concluida BOOLEAN DEFAULT FALSE,
    categoria VARCHAR(255) NOT NULL,
    criada_em DATE
);

CREATE TABLE IF NOT EXISTS users(
    userid BIGINT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(255) NOT NULL
);